version: '3'
services:
  #Build and Run Container
   webpage:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-webpage:latest
    container_name: my-webpage
    restart: unless-stopped
    ports:
      - "80:80"