name: Build Scan and Push Docker Image

on:
  push:
    branches: [ "week-4" ]
  
  workflow_dispatch:

env:
  REPO: swaydevstan/nodejs-api

permissions:
  contents: read
  security-events: write

jobs:

  docker_build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Semantic versioning for Images
      id: versioning
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      with:
        branch: week-4
        tag_prefix: "v"
        major_pattern: "Major:"
        minor_pattern: "feat:"
        bump_each_commit: true
        version_format: ${major}.${minor}.${patch}
        # format: "v${major}.${minor}.${patch}-${increment}"

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Scan for Secrets and Credentials Leak
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Static Code Analysis
      uses: github/codeql-action/init@v2
      with:
          languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    #   uses: codacy/codacy-analysis-cli-action@master
    #   with:
    #       output: static-analysis-results.sarif
    #       format: sarif
  
    # - name: Upload Static Code Analysis results
    #   if: always()
    #   uses: github/codeql-action/upload-sarif@main
    #   with:
    #     sarif_file: static-analysis-results.sarif

    - name: Run Unit Tests
      run: |
            npm i
            npm run test
      
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag ${{ env.REPO }}:${{ steps.versioning.outputs.version }} .

    - name: Run Trivy vulnerability scanner to scan image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.REPO }}:${{ steps.versioning.outputs.version }}'
        format: 'sarif'
        output: 'image-scan-results.sarif'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'


    - name: Upload Trivy scan results to GitHub Security tab
      if: always() #
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'image-scan-results.sarif'

    - name: Log in to DockerHub    
      uses: docker/login-action@v2
      with:            
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Push Image to Registry
      run: docker push ${{ env.REPO }}:${{ steps.versioning.outputs.version }}


