name: Build Scan and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  CONTAINER_REGISTRY: docker.io
  REPO: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Semantic versioning for Images
      id: versioning
      uses: PaulHatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefix: "v"
        major_pattern: "MAJOR CHANGE:"
        minor_pattern: "feat:"
        format: "v${major}.${minor}.${patch}"

    - name: Log in to DockerHub    
      uses: docker/login-action@v2
      with:            
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build --file Dockerfile --tag ${{ env.REPO }}:${{ steps.versioning.outputs.version }} .

    - name: Scan the Docker images
      run: docker scan --file Dockerfile ${{ env.REPO }}:${{ steps.versioning.outputs.version }}
    
    - name: Push Image to the registry.
      run: docker push ${{ env.REPO }}:${{ steps.versioning.outputs.version }} .


