name: Build Scan and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: "dev-accel-task"
  VERSION: "$(date +%s).git.$GIT_REVISION"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
    
    - name: Scan the Docker image
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Log into registry    
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}              
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image to the registry.
      run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}


